services:

  db:
    container_name: ${PG_DB}
    env_file: ".env"
    image: postgres:latest
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    
    volumes:
      - task-managment:/var/lib/postgresql/data

    ports:
      - "${PG_PORT}:5432"

volumes:
  task-managment:
